### ISSUE TITLE
Cannot compile ground station 

### ISSUE THREAD

**Issue by geofrancis** [RomanLut/esp32-cam-fpv#2]
when trying to build the ground station it always errors at imgui, no such file or directory. I tried the original jeanlemotan ground station and it runs so its something with your version.

what version of raspi OS are you using?

> Successfully installed Cython-0.29.37 PySDL2-0.9.16 cocos2d-0.6.10 glfw-2.7.0 imgui-2.0.0 pyglet-1.5.28
pi@ESP32FPV:/esp32-cam-fpv/gs $ make -j4
g++ -MT .o/src/main.o -MD -MP -MF .d/src/main.Td -std=c++17  `sdl2-config --cflags` -O3 -DNDEBUG -ffast-math -funroll-loops -Wall -Isrc -Isrc/utils -I../components/common -I/usr/include/ -I/usr/include/freetype2 -Isrc/imgui/ -Isrc/imgui//backends -DIMGUI_IMPL_OPENGL_ES2  -c -o .o/src/main.o src/main.cpp
g++ -MT .o/src/HUD.o -MD -MP -MF .d/src/HUD.Td -std=c++17  `sdl2-config --cflags` -O3 -DNDEBUG -ffast-math -funroll-loops -Wall -Isrc -Isrc/utils -I../components/common -I/usr/include/ -I/usr/include/freetype2 -Isrc/imgui/ -Isrc/imgui//backends -DIMGUI_IMPL_OPENGL_ES2  -c -o .o/src/HUD.o src/HUD.cpp
g++ -MT .o/src/PI_HAL.o -MD -MP -MF .d/src/PI_HAL.Td -std=c++17  `sdl2-config --cflags` -O3 -DNDEBUG -ffast-math -funroll-loops -Wall -Isrc -Isrc/utils -I../components/common -I/usr/include/ -I/usr/include/freetype2 -Isrc/imgui/ -Isrc/imgui//backends -DIMGUI_IMPL_OPENGL_ES2  -c -o .o/src/PI_HAL.o src/PI_HAL.cpp
g++ -MT .o/src/Comms.o -MD -MP -MF .d/src/Comms.Td -std=c++17  `sdl2-config --cflags` -O3 -DNDEBUG -ffast-math -funroll-loops -Wall -Isrc -Isrc/utils -I../components/common -I/usr/include/ -I/usr/include/freetype2 -Isrc/imgui/ -Isrc/imgui//backends -DIMGUI_IMPL_OPENGL_ES2  -c -o .o/src/Comms.o src/Comms.cpp
In file included from src/PI_HAL.h:3,
                 from src/PI_HAL.cpp:1:
src/IHAL.h:3:10: fatal error: imgui.h: No such file or directory
    3 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:131: .o/src/PI_HAL.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/HUD.cpp:2:
src/IHAL.h:3:10: fatal error: imgui.h: No such file or directory
    3 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:131: .o/src/HUD.o] Error 1
In file included from src/main.cpp:14:
src/IHAL.h:3:10: fatal error: imgui.h: No such file or directory
    3 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:131: .o/src/main.o] Error 1
src/Comms.cpp: In member function ‘void Comms::process_rx_packets()’:
src/Comms.cpp:1103:14: warning: unused variable ‘coding_n’ [-Wunused-variable]
 1103 |     uint32_t coding_n = m_rx_descriptor.coding_n;
      |              ^~~~~~~~
src/Comms.cpp: At global scope:
src/Comms.cpp:34:16: warning: ‘IEEE_HEADER’ defined but not used [-Wunused-variable]
   34 | static uint8_t IEEE_HEADER[] =
      |                ^~~~~~~~~~~
mv -f .d/src/Comms.Td .d/src/Comms.d
pi@ESP32FPV:~/esp32-cam-fpv/gs $

**Comment by RomanLut** [comment]
I am using 5.10.103-v7+ but this error is not related to os version:

```src/IHAL.h:3:10: fatal error: imgui.h: No such file or directory```

You have to fetch dependent mgui repository:

```git submodule update --init --recursive```
```git pull```

**Comment by geofrancis** [comment]
that got me this 

> geo@ESP32FPV:~/esp32-cam-fpv/gs $ git submodule update --init --recursive
Submodule 'components/esp32-camera' (https://github.com/RomanLut/esp32-camera.git) registered for path '../components/esp32-camera'
Submodule 'gs/src/imgui' (https://github.com/ocornut/imgui.git) registered for path 'src/imgui'
Cloning into '/home/geo/esp32-cam-fpv/components/esp32-camera'...
Cloning into '/home/geo/esp32-cam-fpv/gs/src/imgui'...
fatal: remote error: upload-pack: not our ref 9a808e5a935bac8ef6e8ab4d3241ea6d176c06f4
Fetched in submodule path '../components/esp32-camera', but it did not contain 9a808e5a935bac8ef6e8ab4d3241ea6d176c06f4. Direct fetching of that commit failed.

**Comment by RomanLut** [comment]
Fixed repo references, please try again.

**Comment by geofrancis** [comment]
its compiled but its not starting, I have 3 adapters the onboard os wlan0 and 2x ar9271 adapters as specified in the original instructiuons set as wlan1 and wlan2, I assume you have changed the card setup for a pi without wifi?

> geo@ESP32FPV:~/esp32-cam-fpv/gs $ sudo -E DISPLAY=:0 ./gs
width:1280 height:720
(I) src/Comms.cpp: 722: Radiocap header size: 11, IEEE header size: 24
(I) src/Comms.cpp: 582: Opening interface wlan0mon in monitor mode
(E) src/Comms.cpp: 627: Error in pcap_activate: That device doesn't support monitor mode

**Comment by RomanLut** [comment]
1) With built-in wifi/nexmon drivers and 2db dipole, I have range ~20m

2) On the field I am using single rtl8812au card with wfb-ng drivers https://github.com/svpcom/rtl8812au

3) I am starting it like this:
```
cd /home/pi/esp32-cam-fpv
cd gs
sudo airmon-ng check kill
sudo ip link set wlan1 down
sudo iw dev wlan1 set type monitor
sudo ip link set wlan1 up
sudo ./gs -fullscreen 1 -sm 1 -rx wlan1 -tx wlan1
```

**Comment by geofrancis** [comment]
is there an easy way of getting it to run on startup? having to connect a keyboard and mouse when out testing isnt ideal.

**Comment by RomanLut** [comment]
1) I am using bluetooth mouse
2) Create .sh script with lines above and add it to autostart:
https://learn.sparkfun.com/tutorials/how-to-run-a-raspberry-pi-program-on-startup/method-2-autostart

**Comment by geofrancis** [comment]
does dual adapter diversity work?

**Comment by geofrancis** [comment]
this is the install instructions im using.
sudo apt-get update
sudo apt-get upgrade
sudo apt install libdrm-dev libgbm-dev libgles2-mesa-dev libpcap-dev libturbojpeg0-dev libts-dev libsdl2-dev libfreetype6-dev 
git clone https://github.com/RomanLut/esp32-cam-fpv.git
cd ./esp32-cam-fpv/gs
git submodule update --init --recursive
git pull
make -j4

sudo nano fpv.sh

add

> #!/bin/bash
echo "ESP32-FPV STARTUP"
cd /home/pi/esp32-cam-fpv
cd gs
sudo airmon-ng check kill
sudo ip link set wlan1 down
sudo iw dev wlan1 set type monitor
sudo ip link set wlan1 up
sudo ./gs -fullscreen 1 -sm 1 -rx wlan1 -tx wlan1



I cant get the REALTEK drivers to install, the instructions on svpcom aren't very clear. how did you install them ?

**Comment by geofrancis** [comment]
managed to get it installed with this 

`

sudo apt update && sudo apt upgrade
sudo apt install -y raspberrypi-kernel-headers build-essential bc dkms git
mkdir -p ~/src
cd ~/src
git clone https://github.com/morrownr/8812au-20210629.git
cd ~/src/8812au-20210629
sudo ./install-driver.sh`

**Comment by geofrancis** [comment]
hmm some testing shows that its really unstable, its bouncing between 0 and 10fps after running for a few seconds. restarting with the ar9271 is fine.

**Comment by geofrancis** [comment]
its working but im getting barely 1fps, I have tried it on 32 and 64bit pi.

**Comment by geofrancis** [comment]
I had to install the aircrack tools for monitor mode to work correctly but its now working super smooth with the realtek adapter, the signal was really bad on the ar9271 I never realised til I have seen how much better the RSSI is on the realtek.

sudo apt update && sudo apt upgrade
sudo apt install libdrm-dev libgbm-dev libgles2-mesa-dev libpcap-dev libturbojpeg0-dev libts-dev libsdl2-dev libfreetype6-dev 
sudo apt-get install -y aircrack-ng
sudo apt-get install dkms
sudo apt install -y raspberrypi-kernel-headers build-essential bc dkms git

mkdir -p ~/src
cd ~/src
git clone https://github.com/morrownr/8812au-20210629.git
cd ~/src/8812au-20210629
sudo ./install-driver.sh


no config yes restart


git clone https://github.com/RomanLut/esp32-cam-fpv.git
cd ./esp32-cam-fpv/gs
git submodule update --init --recursive
make -j4




sudo nano /home/pi/Desktop/fpv.sh

 

>                                
> #!/bin/bash
> 
> echo "ESP32-FPV STARTUP"
> cd /home/pi/esp32-cam-fpv
> cd gs
> sudo airmon-ng check kill
> sudo ip link set wlan1 down
> sudo iw dev wlan1 set type monitor
> sudo ip link set wlan1 up
> sudo ./gs -fullscreen 1 -sm 1 -rx wlan1 -tx wlan1
> 

CTRL + O      save
ENTER           confirm
CTRL + X       exit

sudo chmod +x /home/pi/Desktop/fpv.sh

**Comment by geofrancis** [comment]
I have been trying to get an OSD to work but they are all made for the older gpu the pi 3 has so I haven't been able to get anything to even start on my pi 4.

**Comment by RomanLut** [comment]
Well I was going to implement MSP Displayport OSD, but it will take a some time, probably a month. I am not activelly working on this project currently.

**Comment by geofrancis** [comment]
Thats cool, it will give me some time to test some hardware and get the basics tested. I have it fotted to a plane and the booster arrived so il hopefully get some range testing done soon.

**Comment by geofrancis** [comment]
what is the current process for installing the groundstation?

**Comment by RomanLut** [comment]
>what is the current process for installing the groundstation?

Please use **release** branch and this instruction https://github.com/RomanLut/esp32-cam-fpv/blob/master/doc/building_gs_image.md

Air unit pinout is here  https://github.com/RomanLut/esp32-cam-fpv?tab=readme-ov-file#air-unit

Now it looks more like a product.

Mavlink RC and DisplayportMSP OSD do work.

There is no OSD for GPIO joystick yet, but REC keys do work and joystick left/right changes resolution.

**Comment by geofrancis** [comment]
im following the install process and its erroring at "cd esp32-cam-fpv" saying no folder when Adding GPIO keys support

**Comment by RomanLut** [comment]
Thanks, fixed guide.

**Comment by geofrancis** [comment]
the method you used to run automatically on startup doesnt work, I reused my method and it started ok 

> mkdir /home/pi/.config/
mkdir /home/pi/.config/autostart
nano /home/pi/.config/autostart/fpv.desktop

    [Desktop Entry]
    Type=Application
    Name=FPV
    Exec=/usr/bin/bash /home/pi/esp32-cam-fpv/gs/launch.sh

save

**Comment by geofrancis** [comment]
im having a slight issue where it wont start when connected to my 1280x800 monitor but it starts when connected to my USB HDMI capture. I tried to change the settings using raspi-config but the resolution setting wont show up it just goes back to the menu.

**Comment by RomanLut** [comment]
I guess it fails because it can not set 1280x720 resolution. Please try adding **-w 1280 -h 800** to gs command line:https://github.com/RomanLut/esp32-cam-fpv/blob/fd70638ed10efec0b8fdd9faf8e61d49eec45f03/gs/launch.sh#L12

**Comment by RomanLut** [comment]
Release branch updated, closes resolution is selected automatically, Closing this thread because issues are solved.
